name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: 147.79.84.97
          username: u860820588
          password: ${{ secrets.SSH_PASSWORD }}
          port: 65002
          source: "."
          target: "public_html/"
          rm: true # Clean directory before deploy
          strip_components: 0 # Keep folder structure
